FROM python:3.11-slim


WORKDIR /app


COPY . /app

RUN apt-get update && \
    apt-get install -y gcc libpq-dev default-libmysqlclient-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
RUN pip install -r requirements.txt


EXPOSE 8000



CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]