version: '3.9'

networks:
  private-network:
    driver: bridge    
  public-network:
    driver: bridge 

volumes:
  cl_auth_db_data:
  cl_residence_db_data:
  cl_messaging_db_data:
  pg_guest_data:

services:

  # RED PÚBLICA #
  CL_web_rp:
    image: cl_web_rp:latest
    build:
      context: ./CL_web_rp
    container_name: CL_web_rp
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - CL_web_fe
    networks:
      - public-network
      - private-network

  CL_desktop_rp:
    image: cl_desktop_rp:latest
    build:
      context: ./CL_desktop_rp
    container_name: CL_desktop_rp
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:     
      - CL_ag
    networks:
      - public-network
      - private-network 

  # RED PRIVADA #

  # PRESENTACIÓN #
  CL_web_fe:
    image: cl_web_fe:latest
    build: 
      context: ./CL_web_fe      
    container_name: CL_web_fe
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
    networks:
      - private-network
  
  # COMUNICACIÓN #
  CL_ag:
    image: cl_ag:latest
    build:
      context: ./CL_ag
    container_name: CL_ag
    networks:
      - private-network

  CL_auth_lb:
    image: cl_auth_lb:latest
    build:
      context: ./CL_auth_lb
    container_name: CL_auth_lb
    depends_on:
      - CL_auth_ms1
      - CL_auth_ms2
      - CL_auth_ms3
    networks: 
      - private-network

  # LÓGICA #
  CL_auth_ms1:
    image: cl_auth_ms
    container_name: CL_auth_ms1
    hostname: cl-auth-ms1
    build:
      context: ./auth-java-component  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://CL_auth_db:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=cincopatodos
    depends_on:
      - CL_auth_db
    networks:
      - private-network

  CL_auth_ms2:
    image: cl_auth_ms
    container_name: CL_auth_ms2
    hostname: cl-auth-ms2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://CL_auth_db:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=cincopatodos
    depends_on:
      - CL_auth_db
    networks:
      - private-network

  CL_auth_ms3:
    image: cl_auth_ms
    container_name: CL_auth_ms3
    hostname: cl-auth-ms3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://CL_auth_db:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=cincopatodos
    depends_on:
      - CL_auth_db
    networks:
      - private-network

  CL_residence_ms:
    image: conjunto-residencial-cl_residence_ms
    container_name: CL_residence-ms
    build:
      context: ./ResidenceCreator-ms  
    depends_on:
      - CL_residence_db
      - CL_guest_db
    env_file:
      - ./ResidenceCreator-ms/.env
    networks:
      - private-network

  CL_messaging_ms:
    image: cl_messaging_ms:latest
    build:
      context: ./MensajeriaYnotificaciones
      dockerfile: Dockerfile.sbt-alpine
    container_name: CL_messaging-ms
    environment:
      SMTP_SECRET_KEY: "claveaes12345678"
      MONGO_URI: "mongodb://root:cincopatodos@cl_messaging_db:27017/correos?authSource=admin"
    command: ["sbt", "run"]
    depends_on:
      - CL_messaging_db
    restart: unless-stopped
    networks:
      - private-network

  CL_stadistics_ms:
    image: cl_stadistics_ms
    build: ./stadistics
    container_name: CL_stadistics_ms
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - CL_ag
      - CL_web_fe
      - CL_residence_ms
      - CL_auth_db
      - CL_residence_db
    environment:
      - POSTGRES_HOST=CL_auth_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cincopatodos
    networks:
      - private-network

  # DATOS #

  CL_auth_db:
    container_name: CL_auth_db
    image: postgres:16.9-alpine3.21 
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cincopatodos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - cl_auth_db_data:/var/lib/postgresql/data
    networks:
      - private-network

  CL_residence_db:
    image: mongo:8.0.9-noble
    container_name: CL_residence_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=cincopatodos
      - MONGO_INITDB_DATABASE=residence_db
    volumes:
      - cl_residence_db_data:/data/db
    networks:
      - private-network

  CL_messaging_db:
    image: mongo:8.0.9-noble
    container_name: CL_messaging_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=cincopatodos
      - MONGO_INITDB_DATABASE=messaging_db
    volumes:
      - cl_messaging_db_data:/data/db
    networks:
      - private-network

  CL_guest_db:
    container_name: CL_guest_db
    image: postgres:16.9-alpine3.21 
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db2
      - POSTGRES_USER=postgres2
      - POSTGRES_PASSWORD=cincopatodos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres2 -d db2"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_guest_data:/var/lib/postgresql/data
    networks:
      - private-network

  kali:
    build:
      context: .
      dockerfile: Dockerfile.kali
    container_name: kali
    tty: true
    stdin_open: true
    privileged: true
    networks:
      - private-network