events {}

http {
     # Definir el upstream para load balancing de las réplicas de cl-auth-ms
    upstream cl-auth-lb {
        server cl-auth-ms1:8080;
        server cl-auth-ms2:8080;
        server cl-auth-ms3:8080;
    }

    server {
        listen 8080;
        server_name localhost;        

        # Proxy para las réplicas de cl-auth-ms
        location / {
            proxy_pass http://cl-auth-lb;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host cl-auth-lb;
            proxy_cache_bypass $http_upgrade;
        }
    }
}